backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

site_url: https://elnur.netlify.app
display_url: https://elnur.netlify.app
logo_url: https://elnur.netlify.app/contents/uploads/icon.png

#publish_mode: editorial_workflow # this will and workflow: draft, in review, ready states
media_folder: "contents/uploads" # Media files will be stored in the repo under contents/uploads

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    description: The description is a great place for tone setting, high level information, and editing guidelines that are specific to a collection.
    folder: "contents/_blogposts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    extension: "json"
    format: "json"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Rating (scale of 1-5)", name: "rating", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}
    
  - name: 'faq' # Used in routes, ie.: /admin/collections/:slug/edit
    label: 'FAQ' # Used in the UI    
    description: The description is a great place for tone setting, high level information, and editing guidelines that are specific to a collection.
    folder: 'contents/_faqs'
    create: true # Allow users to create new documents in this collection
    extension: "json"
    format: "json"
    fields: # The fields each document in this collection have
      - { label: 'Question', name: 'title', widget: 'string', tagname: 'h1' }
      - { label: 'Answer', name: 'body', widget: 'markdown' }